import moment from 'moment'

export default Object.freeze({
    CALENDAR_INITIAL_EVENTS: [
        {
            title: 'Product call',
            theme: 'GREEN',
            startTime: moment().add(-12, 'd').startOf('day'),
            endTime: moment().add(-12, 'd').endOf('day'),
        },
        {
            title: 'Meeting with tech team',
            theme: 'PINK',
            startTime: moment().add(-8, 'd').startOf('day'),
            endTime: moment().add(-8, 'd').endOf('day'),
        },
        {
            title: 'Meeting with Cristina',
            theme: 'PURPLE',
            startTime: moment().add(-2, 'd').startOf('day'),
            endTime: moment().add(-2, 'd').endOf('day'),
        },
        {
            title: 'Meeting with Alex',
            theme: 'BLUE',
            startTime: moment().startOf('day'),
            endTime: moment().endOf('day'),
        },
        {
            title: 'Product Call',
            theme: 'GREEN',
            startTime: moment().startOf('day'),
            endTime: moment().endOf('day'),
        },
        {
            title: 'Client Meeting',
            theme: 'PURPLE',
            startTime: moment().startOf('day'),
            endTime: moment().endOf('day'),
        },
        {
            title: 'Client Meeting',
            theme: 'ORANGE',
            startTime: moment().add(3, 'd').startOf('day'),
            endTime: moment().add(3, 'd').endOf('day'),
        },
        {
            title: 'Product meeting',
            theme: 'PINK',
            startTime: moment().add(5, 'd').startOf('day'),
            endTime: moment().add(5, 'd').endOf('day'),
        },
        {
            title: 'Sales Meeting',
            theme: 'GREEN',
            startTime: moment().add(8, 'd').startOf('day'),
            endTime: moment().add(8, 'd').endOf('day'),
        },
        {
            title: 'Product Meeting',
            theme: 'ORANGE',
            startTime: moment().add(8, 'd').startOf('day'),
            endTime: moment().add(8, 'd').endOf('day'),
        },
        {
            title: 'Marketing Meeting',
            theme: 'PINK',
            startTime: moment().add(8, 'd').startOf('day'),
            endTime: moment().add(8, 'd').endOf('day'),
        },
        {
            title: 'Client Meeting',
            theme: 'GREEN',
            startTime: moment().add(8, 'd').startOf('day'),
            endTime: moment().add(8, 'd').endOf('day'),
        },
        {
            title: 'Sales meeting',
            theme: 'BLUE',
            startTime: moment().add(12, 'd').startOf('day'),
            endTime: moment().add(12, 'd').endOf('day'),
        },
        {
            title: 'Client meeting',
            theme: 'PURPLE',
            startTime: moment().add(16, 'd').startOf('day'),
            endTime: moment().add(16, 'd').endOf('day'),
        },
    ],

    RECENT_TRANSACTIONS: [
        {
            status: 'Success',
            type: 'Withdrawal',
            amount: 100,
            date: moment().endOf('day'),
        },
        {
            status: 'Success',
            type: 'Deposit',
            amount: 190,
            date: moment().add(-1, 'd').endOf('day'),
        },
        {
            status: 'Success',
            type: 'Withdrawal',
            amount: 112,
            date: moment().add(-1, 'd').endOf('day'),
        },
        {
            status: 'Success',
            type: 'Deposit',
            amount: 111,
            date: moment().add(-1, 'd').endOf('day'),
        },
        {
            status: 'Success',
            type: 'Withdrawal',
            amount: 190,
            date: moment().add(-2, 'd').endOf('day'),
        },
        {
            status: 'Success',
            type: 'Withdrawal',
            amount: 230,
            date: moment().add(-2, 'd').endOf('day'),
        },
        {
            status: 'Success',
            type: 'Withdrawal',
            amount: 331,
            date: moment().add(-2, 'd').endOf('day'),
        },
        {
            status: 'Success',
            type: 'Deposit',
            amount: 581,
            date: moment().add(-2, 'd').endOf('day'),
        },
        {
            status: 'Success',
            type: 'Deposit',
            amount: 151,
            date: moment().add(-2, 'd').endOf('day'),
        },
        {
            status: 'Success',
            type: 'Withdrawal',
            amount: 91,
            date: moment().add(-2, 'd').endOf('day'),
        },
        {
            status: 'Success',
            type: 'Withdrawal',
            amount: 161,
            date: moment().add(-3, 'd').endOf('day'),
        },
        {
            status: 'Success',
            type: 'Deposit',
            amount: 121,
            date: moment().add(-3, 'd').endOf('day'),
        },
        {
            status: 'Success',
            type: 'Withdrawal',
            amount: 713,
            date: moment().add(-3, 'd').endOf('day'),
        },
        {
            status: 'Success',
            type: 'Deposit',
            amount: 217,
            date: moment().add(-3, 'd').endOf('day'),
        },
        {
            status: 'Success',
            type: 'Withdrawal',
            amount: 117,
            date: moment().add(-3, 'd').endOf('day'),
        },
        {
            status: 'Success',
            type: 'Withdrawal',
            amount: 612,
            date: moment().add(-3, 'd').endOf('day'),
        },
        {
            status: 'Success',
            type: 'Deposit',
            amount: 631,
            date: moment().add(-3, 'd').endOf('day'),
        },
        {
            status: 'Success',
            type: 'Deposit',
            amount: 151,
            date: moment().add(-3, 'd').endOf('day'),
        },
        {
            status: 'Success',
            type: 'Withdrawal',
            amount: 617,
            date: moment().add(-3, 'd').endOf('day'),
        },
    ],
})
